apiVersion: v1
kind: Service # Handles networking in your k8s cluster
metadata:
    name: client-node-port

spec:
    type: NodePort # Exposes a contaier to the outside world. Only good for dev purposes.
    ports:
        - 
            port: 3050            # Port inside of the k8s cluster
            targetPort: 3000    # Port connecting to the destination pod
            nodePort: 31515     # Port we type into our browser to connect to the pod. (localhost:31515, always b/w 30000-32767)
    selector: # Selects the object it needs to direct traffic to using the SELECTOR LABEL system (selecting specific tags)
        component: web